# vim:sw=2:et:

sudo: false
language: erlang
notifications:
  email:
    - alerts@rabbitmq.com
addons:
  apt:
    packages:
      - awscli
      - maven
      - xsltproc
cache:
  apt: true
env:
  global:
    - secure: MRnOlh923a0WMNykrdU1eH3ZPkSDwHfooNmvXJqeV5f7xkM22mdlsp21LVXDXIrFc3yavumesSIjKri/cQAXBEPgao21/ERTMRtViTZUSwAlxLIR5s+zfGxdju/TJcm+VVaIPulBi6ouhh4bzHSwyhEgzgYLgKHkR4p2pSON1qE=
    - secure: G1cXSA1W/yoZmDy9iQ3FnVMQ1vEw1J1t8tZzSPPa895X3kGmivk70ujei7bILRCSb5/xVnpF1dTllqXbnkSd9Rr8pfLSvt6V1dk0tRVHMXhAVuGSo/9YTKVd/2E5bOl48qxHp6ipAtKsYuEi64SmqsWsZ/QFp1MOmbCnkyqRnc0=

otp_release:
  - "R16B03-1"
  - "19.3"
  - "20.1"

before_script:
  # The checkout made by Travis is a "detached HEAD" and branches
  # information is missing. Our Erlang.mk's git_rmq fetch method relies
  # on it, so we need to restore it.
  #
  # We simply fetch master and, if it exists, v3.6.x branches. A branch
  # is created, pointing to the detached HEAD.
  - |
    git checkout -B "${TRAVIS_TAG:-${TRAVIS_BRANCH}}"
    git remote add upstream https://github.com/$TRAVIS_REPO_SLUG.git
    git fetch upstream v3.6.x:v3.6.x || :
    git fetch upstream master:master || :

script:
  - make xref
  - make tests

after_failure:
  - |
    cd "$TRAVIS_BUILD_DIR"
    if test -d logs && test "$AWS_ACCESS_KEY_ID" && test "$AWS_SECRET_ACCESS_KEY"; then
      archive_name="$(basename "$TRAVIS_REPO_SLUG")-$TRAVIS_JOB_NUMBER"

      tar -c --transform "s/^logs/${archive_name}/" -f - logs | \
        xz > "${archive_name}.tar.xz"

      aws s3 cp "${archive_name}.tar.xz" s3://server-release-pipeline/travis-ci-logs/ \
        --region eu-west-1 \
        --acl public-read
    fi
